---
- hosts: all
  remote_user: root
  vars_files:
    - "{{ playbook_dir }}/kubernetes/vars/default_vars.yml"
    - "{{ playbook_dir }}/common/vars/default_vars.yml"
  roles:
    - "{{ playbook_dir }}/kubernetes/roles/prerequisites"
    - "{{ playbook_dir }}/common/roles/golang"
    - "{{ playbook_dir }}/common/roles/kubevirt"

- hosts: masters
  remote_user: root
  vars_files:
    - "{{ playbook_dir }}/kubernetes/vars/default_vars.yml"
  roles:
    - "{{ playbook_dir }}/kubernetes/roles/master"

- hosts: nodes
  remote_user: root
  vars_files:
    - "{{ playbook_dir }}/kubernetes/vars/default_vars.yml"
  roles:
    - "{{ playbook_dir }}/kubernetes/roles/node"


