- hosts: all
  remote_user: root
  pre_tasks:
    - name: override go-dev variables
      include_vars: "{{ playbook_dir }}/common/vars/default_vars.yml"
      tags: go
  roles:
    - role: "andrewrothstein.go-dev"
      tags: go
    - role: "{{ playbook_dir }}/common/roles/kubevirt"
      tags: kubevirt
