---
docker_tag: 'v0.1.0'
docker_prefix: kubevirt
primary_nic: eth0


wait_kubevirt_rollout: True

# Wait by default for 10 minutes for kubevirt objects
until_delay: 30
until_retries: 20

# ansible.kubernetes-modules
install_python_requirements: True
clone_path: /tmp/kubevirt

# see https://github.com/kubevirt/kubevirt/tree/master/manifests
# for versions currently:
# dev, release, testing
manifests_version: release
manifests_path: "{{ clone_path }}/manifests/{{ manifests_version }}/"
kubeconfig: /root/.kube/config
#kubeconfig: /etc/kubernetes/admin.conf
namespace: kube-system

repo: https://github.com/kubevirt/kubevirt
checkout_path: /tmp/kubevirt

master_ip: "{{ hostvars[groups['masters'][0]]['ansible_default_ipv4']['address'] }}"
wait_kubevirt_rollout: True

